---

plugins:
  - jest
  - babel
env:
  browser: true
  jest: true
  node: true
extends:
  - airbnb-base
  - 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0

